name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  eslint_prettier:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18.x]
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing deps
        run: |
          npm ci
      - name: Build
        run: |
          npx eslint --ext .js,.jsx,.ts,.tsx ./
          npx prettier --check **/*.{js,jsx,ts,tsx,json}